version: 2.1
jobs:
  build:
    docker:
      - image: rolandjitsu/gcloud-node
    working_directory: ~/kataIdukay
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install Dependecies
          command: npm install
      - run: 
          name: Tests
          command: npm run test
      - run: 
          name: Deploy
          command: ./deployment.sh
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: development