version: 2.1
jobs:
  deploy_project:
    docker:
      - image: rolandjitsu/gcloud-node
    working_directory: ~/kataIdukay
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install Dependecies
          command: npm install
      - run: 
          name: Copy build files to server
          command: cp ./ci/deployment.sh
      - run: 
          name: Deploy
          command: ./deployment.sh
workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master